import type { ServiceCategory, ServiceSpec, ServiceType, ProviderSkin } from '@/types';

export const CATALOG: Record<ServiceType, ServiceSpec> = {
  client: {
    type: 'client',
    label: 'Client / Users',
    category: 'source',
    icon: 'Globe',
    costPerMonth: 0,
    capacityRps: Infinity,
    latencyMs: 0,
    availability: 1.0,
  },
  cdn: {
    type: 'cdn',
    label: 'CDN',
    category: 'edge',
    icon: 'Zap',
    costPerMonth: 20,
    capacityRps: 1_000_000,
    latencyMs: 5,
    availability: 0.999,
    cacheHitRatio: 0.9,
  },
  apiGateway: {
    type: 'apiGateway',
    label: 'API Gateway',
    category: 'edge',
    icon: 'GitMerge',
    costPerMonth: 30,
    capacityRps: 50_000,
    latencyMs: 5,
    availability: 0.999,
  },
  loadBalancer: {
    type: 'loadBalancer',
    label: 'Load Balancer',
    category: 'networking',
    icon: 'Network',
    costPerMonth: 25,
    capacityRps: 100_000,
    latencyMs: 2,
    availability: 0.9999,
  },
  computeInstance: {
    type: 'computeInstance',
    label: 'Compute Instance',
    category: 'compute',
    icon: 'Server',
    costPerMonth: 40,
    capacityRps: 2_000,
    latencyMs: 20,
    availability: 0.99,
  },
  autoScalingGroup: {
    type: 'autoScalingGroup',
    label: 'Auto Scaling Group',
    category: 'compute',
    icon: 'Layers',
    costPerMonth: 40,
    capacityRps: 2_000,
    latencyMs: 20,
    availability: 0.999,
    isRedundant: true,
    scalable: { min: 2, max: 10, default: 3 },
  },
  serverless: {
    type: 'serverless',
    label: 'Serverless',
    category: 'compute',
    icon: 'Cpu',
    costPerMonth: 0.20,
    capacityRps: 100_000,
    latencyMs: 50,
    availability: 0.9995,
  },
  cache: {
    type: 'cache',
    label: 'Cache (Redis)',
    category: 'data',
    icon: 'Gauge',
    costPerMonth: 30,
    capacityRps: 200_000,
    latencyMs: 1,
    availability: 0.999,
    cacheHitRatio: 0.8,
  },
  sqlPrimary: {
    type: 'sqlPrimary',
    label: 'SQL Primary DB',
    category: 'data',
    icon: 'Database',
    costPerMonth: 60,
    capacityRps: 5_000,
    latencyMs: 15,
    availability: 0.99,
  },
  sqlReplica: {
    type: 'sqlReplica',
    label: 'SQL Read Replica',
    category: 'data',
    icon: 'DatabaseBackup',
    costPerMonth: 50,
    capacityRps: 5_000,
    latencyMs: 15,
    availability: 0.99,
    scalable: { min: 1, max: 4, default: 1 },
  },
  nosqlDb: {
    type: 'nosqlDb',
    label: 'NoSQL Database',
    category: 'data',
    icon: 'Table',
    costPerMonth: 70,
    capacityRps: 50_000,
    latencyMs: 10,
    availability: 0.9995,
  },
  objectStorage: {
    type: 'objectStorage',
    label: 'Object Storage',
    category: 'data',
    icon: 'HardDrive',
    costPerMonth: 15,
    capacityRps: 1_000_000,
    latencyMs: 30,
    availability: 0.99999,
  },
  messageQueue: {
    type: 'messageQueue',
    label: 'Message Queue',
    category: 'async',
    icon: 'MessageSquare',
    costPerMonth: 20,
    capacityRps: 100_000,
    latencyMs: 0,
    availability: 0.999,
  },
  worker: {
    type: 'worker',
    label: 'Worker / Consumer',
    category: 'async',
    icon: 'Cog',
    costPerMonth: 35,
    capacityRps: 2_000,
    latencyMs: 0,
    availability: 0.99,
    scalable: { min: 1, max: 8, default: 2 },
  },
  // v3 additions
  dns: {
    type: 'dns',
    label: 'DNS Server',
    category: 'edge',
    icon: 'Globe',
    costPerMonth: 10,
    capacityRps: 1_000_000,
    latencyMs: 10,
    availability: 0.9999,
  },
  rateLimiter: {
    type: 'rateLimiter',
    label: 'Rate Limiter',
    category: 'networking',
    icon: 'Gauge',
    costPerMonth: 15,
    capacityRps: 150_000,
    latencyMs: 2,
    availability: 0.999,
  },
  containerCluster: {
    type: 'containerCluster',
    label: 'Container Cluster',
    category: 'compute',
    icon: 'Boxes',
    costPerMonth: 50,
    capacityRps: 3_000,
    latencyMs: 18,
    availability: 0.999,
    scalable: { min: 3, max: 20, default: 3 },
  },
  edgeFunction: {
    type: 'edgeFunction',
    label: 'Edge Function',
    category: 'compute',
    icon: 'Zap',
    costPerMonth: 0.25, // dynamic $0.25 / 1k rps in cost math
    capacityRps: 200_000,
    latencyMs: 8,
    availability: 0.9995,
  },
  gpuInstance: {
    type: 'gpuInstance',
    label: 'GPU Instance',
    category: 'compute',
    icon: 'Cpu',
    costPerMonth: 120,
    capacityRps: 1_000,
    latencyMs: 25,
    availability: 0.99,
    scalable: { min: 1, max: 8, default: 1 },
  },
  searchIndex: {
    type: 'searchIndex',
    label: 'Search Index',
    category: 'data',
    icon: 'Search',
    costPerMonth: 55,
    capacityRps: 30_000,
    latencyMs: 12,
    availability: 0.999,
  },
  timeSeriesDb: {
    type: 'timeSeriesDb',
    label: 'TimeSeries DB',
    category: 'data',
    icon: 'Activity',
    costPerMonth: 45,
    capacityRps: 40_000,
    latencyMs: 8,
    availability: 0.999,
  },
  dataWarehouse: {
    type: 'dataWarehouse',
    label: 'Data Warehouse',
    category: 'data',
    icon: 'Database',
    costPerMonth: 90,
    capacityRps: 5_000,
    latencyMs: 200,
    availability: 0.999,
  },
  blockStorage: {
    type: 'blockStorage',
    label: 'Block Storage (SSD)',
    category: 'data',
    icon: 'HardDrive',
    costPerMonth: 10,
    capacityRps: Infinity,
    latencyMs: 3,
    availability: 0.9999,
    scalable: { min: 1, max: 10, default: 1 },
  },
  pubSub: {
    type: 'pubSub',
    label: 'Pub/Sub Event Bus',
    category: 'async',
    icon: 'Radio',
    costPerMonth: 25,
    capacityRps: 200_000,
    latencyMs: 0,
    availability: 0.999,
  },
  streamProcessor: {
    type: 'streamProcessor',
    label: 'Stream Processor',
    category: 'async',
    icon: 'RefreshCw',
    costPerMonth: 60,
    capacityRps: 500_000,
    latencyMs: 0,
    availability: 0.9995,
  },
  scheduler: {
    type: 'scheduler',
    label: 'Cron Scheduler',
    category: 'async',
    icon: 'Calendar',
    costPerMonth: 5,
    capacityRps: Infinity,
    latencyMs: 0,
    availability: 0.999,
  },
  workflowOrchestrator: {
    type: 'workflowOrchestrator',
    label: 'Workflow Orchestrator',
    category: 'async',
    icon: 'GitBranch',
    costPerMonth: 30,
    capacityRps: Infinity,
    latencyMs: 0,
    availability: 0.999,
  },
  waf: {
    type: 'waf',
    label: 'WAF',
    category: 'security',
    icon: 'ShieldAlert',
    costPerMonth: 35,
    capacityRps: 80_000,
    latencyMs: 4,
    availability: 0.999,
  },
  ddosProtection: {
    type: 'ddosProtection',
    label: 'DDoS Protection',
    category: 'security',
    icon: 'Shield',
    costPerMonth: 40,
    capacityRps: 1_000_000,
    latencyMs: 3,
    availability: 0.9999,
  },
  authService: {
    type: 'authService',
    label: 'Auth Service',
    category: 'security',
    icon: 'Lock',
    costPerMonth: 30,
    capacityRps: 40_000,
    latencyMs: 8,
    availability: 0.999,
  },
  secretsManager: {
    type: 'secretsManager',
    label: 'Secrets Manager',
    category: 'security',
    icon: 'Key',
    costPerMonth: 15,
    capacityRps: Infinity,
    latencyMs: 0,
    availability: 0.9999,
  },
  monitoring: {
    type: 'monitoring',
    label: 'Monitoring System',
    category: 'observability',
    icon: 'Eye',
    costPerMonth: 20,
    capacityRps: Infinity,
    latencyMs: 0,
    availability: 0.999,
  },
  logging: {
    type: 'logging',
    label: 'Central Logging',
    category: 'observability',
    icon: 'FileText',
    costPerMonth: 15,
    capacityRps: Infinity,
    latencyMs: 0,
    availability: 0.999,
  },
  alerting: {
    type: 'alerting',
    label: 'Alerting Manager',
    category: 'observability',
    icon: 'Bell',
    costPerMonth: 10,
    capacityRps: Infinity,
    latencyMs: 0,
    availability: 0.999,
  },
  tracing: {
    type: 'tracing',
    label: 'Distributed Tracing',
    category: 'observability',
    icon: 'Route',
    costPerMonth: 20,
    capacityRps: Infinity,
    latencyMs: 0,
    availability: 0.999,
  },
};

export const PALETTE_ORDER: ServiceType[] = [
  'client',
  'cdn', 'apiGateway', 'dns',
  'loadBalancer', 'rateLimiter',
  'computeInstance', 'autoScalingGroup', 'serverless', 'containerCluster', 'edgeFunction', 'gpuInstance',
  'cache', 'sqlPrimary', 'sqlReplica', 'nosqlDb', 'objectStorage', 'searchIndex', 'timeSeriesDb', 'dataWarehouse', 'blockStorage',
  'messageQueue', 'worker', 'pubSub', 'streamProcessor', 'scheduler', 'workflowOrchestrator',
  'waf', 'ddosProtection', 'authService', 'secretsManager',
  'monitoring', 'logging', 'alerting', 'tracing',
];

// CSS custom property names (from §3.2 of the build plan)
export const CATEGORY_COLOR: Record<ServiceCategory, string> = {
  source:        '#9B5DE5',
  edge:          '#22B8FF',
  networking:    '#FF8A3D',
  compute:       '#1DD3A0',
  data:          '#3D5AFE',
  async:         '#FF6FA5',
  security:      '#3B4252',
  observability: '#64748B',
};

export const CATEGORY_LABEL: Record<ServiceCategory, string> = {
  source:        'Source',
  edge:          'Edge',
  networking:    'Networking',
  compute:       'Compute',
  data:          'Data',
  async:         'Async',
  security:      'Security',
  observability: 'Observability',
};

export const CATEGORIES: ServiceCategory[] = [
  'source', 'edge', 'networking', 'compute', 'data', 'async', 'security', 'observability',
];

/** One-line "what it does / when to use it" blurb shown in the palette. */
export const SERVICE_DESC: Record<ServiceType, string> = {
  client:           'The users hitting your system — every request starts here.',
  cdn:              'Caches static files at the edge, near users. Cuts latency for images, video and JS/CSS.',
  apiGateway:       'A single front door that routes, authenticates and throttles API traffic.',
  dns:              'Resolves your domain to an address — the very first hop of every request.',
  loadBalancer:     'Spreads traffic across many compute nodes so no single box gets overwhelmed.',
  rateLimiter:      'Caps requests per client to fend off abuse and shield what is downstream.',
  computeInstance:  'A single server running your app. Simple, but a single point of failure (~2k rps).',
  autoScalingGroup: 'A pool of servers that grows and shrinks with load — redundant by design.',
  serverless:       'Functions that scale to zero and burst on demand. Great for spiky traffic.',
  containerCluster: 'Orchestrated containers that autoscale — flexible compute for bigger apps.',
  edgeFunction:     'Tiny functions that run at the edge, close to users, for ultra-low latency.',
  gpuInstance:      'GPU-backed compute for ML inference, transcoding and heavy number-crunching.',
  cache:            'In-memory store (Redis) for hot data — absorbs read load off the database.',
  sqlPrimary:       'Relational source of truth. Strong consistency, but limited write throughput.',
  sqlReplica:       'Read-only copies of the SQL primary — scale reads without touching writes.',
  nosqlDb:          'Key-value / document store that scales reads and writes very wide.',
  objectStorage:    'Cheap, durable blob storage for files, images, uploads and backups.',
  searchIndex:      'Full-text search engine for fast queries over large datasets.',
  timeSeriesDb:     'Built for metrics and timestamped data at very high write rates.',
  dataWarehouse:    'Columnar store for big analytical queries — slow, not for live traffic.',
  blockStorage:     'Fast SSD volumes attached to compute — low-latency persistent disk.',
  messageQueue:     'Buffers work for later — decouples producers from slow consumers.',
  worker:           'Background consumer that drains a queue and does slow work off the request path.',
  pubSub:           'Fan-out event bus — one message delivered to many subscribers.',
  streamProcessor:  'Crunches high-volume event streams in real time.',
  scheduler:        'Runs jobs on a cron schedule — cleanups, reports, nightly batches.',
  workflowOrchestrator: 'Coordinates multi-step, long-running workflows with retries.',
  waf:              'Web app firewall — blocks malicious requests before they reach your app.',
  ddosProtection:   'Absorbs and filters volumetric attacks at the edge.',
  authService:      'Handles login, tokens and identity — gate private data behind it.',
  secretsManager:   'Securely stores API keys, passwords and certificates.',
  monitoring:       'Dashboards and metrics so you can see what your system is doing.',
  logging:          'Centralised logs for debugging and audit trails.',
  alerting:         'Pages the on-call crew the moment something crosses a threshold.',
  tracing:          'Follows one request across services to find the slow hop.',
};


export const PROVIDER_LABELS: Record<ProviderSkin, Partial<Record<ServiceType, string>>> = {
  generic: {},  // fallback: use catalog spec.label

  'aws-style': {
    cdn:                'CloudFront-style',
    apiGateway:         'API GW-style',
    loadBalancer:       'ALB-style',
    computeInstance:    'EC2-style',
    autoScalingGroup:   'ASG-style',
    serverless:         'Lambda-style',
    containerCluster:   'EKS-style',
    edgeFunction:       'Lambda@Edge-style',
    gpuInstance:        'P-Instance-style',
    cache:              'ElastiCache-style',
    sqlPrimary:         'RDS Primary-style',
    sqlReplica:         'RDS Replica-style',
    nosqlDb:            'DynamoDB-style',
    objectStorage:      'S3-style',
    searchIndex:        'OpenSearch-style',
    timeSeriesDb:       'Timestream-style',
    dataWarehouse:      'Redshift-style',
    blockStorage:       'EBS-style',
    messageQueue:       'SQS-style',
    worker:             'EC2 Worker-style',
    pubSub:             'SNS-style',
    streamProcessor:    'Kinesis-style',
    scheduler:          'EventBridge-style',
    workflowOrchestrator: 'Step Fn-style',
    waf:                'WAF-style',
    ddosProtection:     'Shield-style',
    authService:        'Cognito-style',
    secretsManager:     'Secrets Mgr-style',
    monitoring:         'CloudWatch-style',
    logging:            'CloudTrail-style',
    alerting:           'CW Alarms-style',
    tracing:            'X-Ray-style',
    dns:                'Route53-style',
    rateLimiter:        'API Throttle-style',
  },

  'azure-style': {
    cdn:                'Front Door-style',
    apiGateway:         'API Mgmt-style',
    loadBalancer:       'Load Balancer-style',
    computeInstance:    'VM-style',
    autoScalingGroup:   'VMSS-style',
    serverless:         'Functions-style',
    containerCluster:   'AKS-style',
    edgeFunction:       'CDN Rules-style',
    gpuInstance:        'NC VM-style',
    cache:              'Redis Cache-style',
    sqlPrimary:         'SQL DB-style',
    sqlReplica:         'SQL Replica-style',
    nosqlDb:            'Cosmos DB-style',
    objectStorage:      'Blob Storage-style',
    searchIndex:        'AI Search-style',
    timeSeriesDb:       'TSI-style',
    dataWarehouse:      'Synapse-style',
    blockStorage:       'Managed Disk-style',
    messageQueue:       'Service Bus-style',
    worker:             'Worker Role-style',
    pubSub:             'Event Grid-style',
    streamProcessor:    'Event Hubs-style',
    scheduler:          'Logic Apps-style',
    workflowOrchestrator: 'Durable Fn-style',
    waf:                'App GW WAF-style',
    ddosProtection:     'DDoS Prot-style',
    authService:        'Entra ID-style',
    secretsManager:     'Key Vault-style',
    monitoring:         'Monitor-style',
    logging:            'Log Analytics-style',
    alerting:           'Alerts-style',
    tracing:            'AppInsights-style',
    dns:                'DNS Zone-style',
    rateLimiter:        'API Rate-style',
  },

  'gcp-style': {
    cdn:                'Cloud CDN-style',
    apiGateway:         'Apigee-style',
    loadBalancer:       'Cloud LB-style',
    computeInstance:    'GCE VM-style',
    autoScalingGroup:   'MIG-style',
    serverless:         'Cloud Run-style',
    containerCluster:   'GKE-style',
    edgeFunction:       'CF@Edge-style',
    gpuInstance:        'A100 VM-style',
    cache:              'Memorystore-style',
    sqlPrimary:         'Cloud SQL-style',
    sqlReplica:         'SQL Replica-style',
    nosqlDb:            'Firestore-style',
    objectStorage:      'GCS-style',
    searchIndex:        'Vertex Search-style',
    timeSeriesDb:       'BigTable-style',
    dataWarehouse:      'BigQuery-style',
    blockStorage:       'Persistent Disk-style',
    messageQueue:       'Pub/Sub-style',
    worker:             'GCE Worker-style',
    pubSub:             'Pub/Sub Fan-style',
    streamProcessor:    'Dataflow-style',
    scheduler:          'Cloud Scheduler-style',
    workflowOrchestrator: 'Workflows-style',
    waf:                'Cloud Armor-style',
    ddosProtection:     'Armor DDoS-style',
    authService:        'Identity Pf-style',
    secretsManager:     'Secret Mgr-style',
    monitoring:         'Cloud Mon-style',
    logging:            'Cloud Logging-style',
    alerting:           'Alerting-style',
    tracing:            'Cloud Trace-style',
    dns:                'Cloud DNS-style',
    rateLimiter:        'Rate Limit-style',
  },
};

/** Returns the display label for a node, respecting active provider skin. */
export function getNodeLabel(type: ServiceType, skin: ProviderSkin, customLabel?: string): string {
  if (customLabel) return customLabel;
  const override = PROVIDER_LABELS[skin][type];
  return override ?? CATALOG[type].label;
}

