import type { Scenario } from '@/types';

export const SCENARIOS: Scenario[] = [
  {
    id: 'hello-scale',
    title: 'Hello, Scale',
    brief: "Your startup just got featured on TechCrunch. Traffic is spiking fast — but the board is empty. Wire up a basic architecture before the servers melt.",
    targetRps: 1_000,
    maxLatencyMs: 200,
    budgetUsd: 200,
    slaAvailability: 0.99,
    readShare: 0.7,
    staticShare: 0.1,
    requiresPersistence: true,
    requiresHA: false,
    difficulty: 'Beginner',
    // Empty board — tutorial; player builds from scratch
    startingArchitecture: undefined,
  },
  {
    id: 'news-site',
    title: 'Read-Heavy News Site',
    brief: "GlobalNews is creaking under 20k readers/sec. The current setup has a compute instance wired straight to a SQL primary — no cache, no CDN. Users are seeing 800ms pages. Fix it.",
    targetRps: 20_000,
    maxLatencyMs: 100,
    budgetUsd: 400,
    slaAvailability: 0.999,
    readShare: 0.95,
    staticShare: 0.4,
    requiresPersistence: true,
    requiresHA: false,
    difficulty: 'Intermediate',
    startingArchitecture: {
      nodes: [
        { id: 'client-node',   type: 'client',          label: 'Client / Users',   position: { x: 80,  y: 200 } },
        { id: 'compute-1',     type: 'computeInstance', label: 'Compute Instance', position: { x: 380, y: 200 } },
        { id: 'sql-1',         type: 'sqlPrimary',      label: 'SQL Primary DB',   position: { x: 680, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'client-node', target: 'compute-1' },
        { id: 'e2', source: 'compute-1',   target: 'sql-1' },
      ],
    },
  },
  {
    id: 'black-friday',
    title: 'Black Friday Spike',
    brief: "ShopFast's Black Friday drop is in 30 minutes. The current architecture has a single compute instance behind a load balancer — already struggling at 5k RPS. You need 80k. Go.",
    targetRps: 80_000,
    maxLatencyMs: 150,
    budgetUsd: 600,
    slaAvailability: 0.9995,
    readShare: 0.6,
    staticShare: 0.2,
    requiresPersistence: true,
    requiresHA: true,
    difficulty: 'Advanced',
    startingArchitecture: {
      nodes: [
        { id: 'client-node', type: 'client',          label: 'Client / Users',   position: { x: 80,  y: 200 } },
        { id: 'lb-1',        type: 'loadBalancer',    label: 'Load Balancer',    position: { x: 330, y: 200 } },
        { id: 'compute-1',   type: 'computeInstance', label: 'Compute Instance', position: { x: 580, y: 200 } },
        { id: 'sql-1',       type: 'sqlPrimary',      label: 'SQL Primary DB',   position: { x: 830, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'client-node', target: 'lb-1' },
        { id: 'e2', source: 'lb-1',        target: 'compute-1' },
        { id: 'e3', source: 'compute-1',   target: 'sql-1' },
      ],
    },
  },
  {
    id: 'survive-outage',
    title: 'Survive the Outage',
    brief: "PagerDuty just fired. A zone is going dark in 5 minutes. The current architecture has single points of failure everywhere — single compute, single DB, no redundancy. Get to four nines before the timer runs out.",
    targetRps: 10_000,
    maxLatencyMs: 150,
    budgetUsd: 800,
    slaAvailability: 0.9999,
    readShare: 0.5,
    staticShare: 0.1,
    requiresPersistence: true,
    requiresHA: true,
    difficulty: 'Expert',
    startingArchitecture: {
      nodes: [
        { id: 'client-node', type: 'client',          label: 'Client / Users',   position: { x: 80,  y: 200 } },
        { id: 'lb-1',        type: 'loadBalancer',    label: 'Load Balancer',    position: { x: 330, y: 160 } },
        { id: 'compute-1',   type: 'computeInstance', label: 'Compute Instance', position: { x: 580, y: 160 } },
        { id: 'sql-1',       type: 'sqlPrimary',      label: 'SQL Primary DB',   position: { x: 830, y: 160 } },
      ],
      edges: [
        { id: 'e1', source: 'client-node', target: 'lb-1' },
        { id: 'e2', source: 'lb-1',        target: 'compute-1' },
        { id: 'e3', source: 'compute-1',   target: 'sql-1' },
      ],
    },
  },
  {
    id: 'upload-pipeline',
    title: 'Async Upload Pipeline',
    brief: "StreamVault users upload videos inline — the upload endpoint is also doing transcoding synchronously. It times out constantly. Decouple the pipeline: accept uploads fast, process in the background.",
    targetRps: 5_000,
    maxLatencyMs: 300,
    budgetUsd: 500,
    slaAvailability: 0.999,
    readShare: 0.3,
    staticShare: 0.0,
    requiresPersistence: true,
    requiresHA: false,
    difficulty: 'Intermediate',
    startingArchitecture: {
      nodes: [
        { id: 'client-node', type: 'client',          label: 'Client / Users',   position: { x: 80,  y: 200 } },
        { id: 'compute-1',   type: 'computeInstance', label: 'Compute Instance', position: { x: 380, y: 200 } },
        { id: 'sql-1',       type: 'sqlPrimary',      label: 'SQL Primary DB',   position: { x: 680, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'client-node', target: 'compute-1' },
        { id: 'e2', source: 'compute-1',   target: 'sql-1' },
      ],
    },
  },
  {
    id: 'under-attack',
    title: 'DDoS Botnet Attack',
    brief: "A botnet is hammering your site with 150k RPS. The current setup has a single load balancer and compute instance. Shield the entry point, throttle requests, and block malicious vectors before the app collapses.",
    targetRps: 150_000,
    maxLatencyMs: 150,
    budgetUsd: 500,
    slaAvailability: 0.999,
    readShare: 0.8,
    staticShare: 0.2,
    requiresPersistence: true,
    requiresHA: true,
    difficulty: 'Expert',
    startingArchitecture: {
      nodes: [
        { id: 'client-node', type: 'client',          label: 'Client / Users',   position: { x: 80,  y: 220 } },
        { id: 'lb-1',        type: 'loadBalancer',    label: 'Load Balancer',    position: { x: 350, y: 220 } },
        { id: 'compute-1',   type: 'computeInstance', label: 'Compute Instance', position: { x: 580, y: 220 } },
        { id: 'sql-1',       type: 'sqlPrimary',      label: 'SQL Primary DB',   position: { x: 810, y: 220 } },
      ],
      edges: [
        { id: 'e1', source: 'client-node', target: 'lb-1' },
        { id: 'e2', source: 'lb-1',        target: 'compute-1' },
        { id: 'e3', source: 'compute-1',   target: 'sql-1' },
      ],
    },
  },
  {
    id: 'search-everything',
    title: 'Product Search Jam',
    brief: "Users searching products are timing out. The read-heavy load (30k RPS, 95% reads) is hitting a SQL Primary database directly. Shift read queries off the primary database into a search index and cache.",
    targetRps: 30_000,
    maxLatencyMs: 80,
    budgetUsd: 450,
    slaAvailability: 0.999,
    readShare: 0.95,
    staticShare: 0.1,
    requiresPersistence: true,
    requiresHA: false,
    difficulty: 'Intermediate',
    startingArchitecture: {
      nodes: [
        { id: 'client-node', type: 'client',          label: 'Client / Users',   position: { x: 80,  y: 220 } },
        { id: 'compute-1',   type: 'computeInstance', label: 'Compute Instance', position: { x: 380, y: 220 } },
        { id: 'sql-1',       type: 'sqlPrimary',      label: 'SQL Primary DB',   position: { x: 680, y: 220 } },
      ],
      edges: [
        { id: 'e1', source: 'client-node', target: 'compute-1' },
        { id: 'e2', source: 'compute-1',   target: 'sql-1' },
      ],
    },
  },
  {
    id: 'going-global',
    title: 'Going Global',
    brief: "Your app has gone viral overseas. Latency is awful (exceeding 200ms) because requests are traveling across continents. Implement edge routing and caching to bring the content closer to users.",
    targetRps: 40_000,
    maxLatencyMs: 50,
    budgetUsd: 600,
    slaAvailability: 0.9995,
    readShare: 0.9,
    staticShare: 0.5,
    requiresPersistence: true,
    requiresHA: true,
    difficulty: 'Advanced',
    startingArchitecture: {
      nodes: [
        { id: 'client-node', type: 'client',          label: 'Client / Users',   position: { x: 80,  y: 220 } },
        { id: 'lb-1',        type: 'loadBalancer',    label: 'Load Balancer',    position: { x: 330, y: 220 } },
        { id: 'compute-1',   type: 'computeInstance', label: 'Compute Instance', position: { x: 580, y: 220 } },
        { id: 'sql-1',       type: 'sqlPrimary',      label: 'SQL Primary DB',   position: { x: 830, y: 220 } },
      ],
      edges: [
        { id: 'e1', source: 'client-node', target: 'lb-1' },
        { id: 'e2', source: 'lb-1',        target: 'compute-1' },
        { id: 'e3', source: 'compute-1',   target: 'sql-1' },
      ],
    },
  },
  {
    id: 'blind-outage',
    title: 'Flying Blind Outage',
    brief: "Your service is suffering intermittent outages, but there are no monitoring dashboards to diagnose why. Re-architect the system for high availability and set up monitoring and alerting alerts to keep the ops crew informed.",
    targetRps: 12_000,
    maxLatencyMs: 150,
    budgetUsd: 550,
    slaAvailability: 0.9999,
    readShare: 0.5,
    staticShare: 0.2,
    requiresPersistence: true,
    requiresHA: true,
    difficulty: 'Expert',
    startingArchitecture: {
      nodes: [
        { id: 'client-node', type: 'client',          label: 'Client / Users',   position: { x: 80,  y: 220 } },
        { id: 'compute-1',   type: 'computeInstance', label: 'Compute Instance', position: { x: 380, y: 220 } },
        { id: 'sql-1',       type: 'sqlPrimary',      label: 'SQL Primary DB',   position: { x: 680, y: 220 } },
      ],
      edges: [
        { id: 'e1', source: 'client-node', target: 'compute-1' },
        { id: 'e2', source: 'compute-1',   target: 'sql-1' },
      ],
    },
  },
  {
    id: 'transcode-storm',
    title: 'Video Transcode Storm',
    brief: "User video uploads are crushing the compute instance, blocking normal traffic. Decouple the upload queue using an async stream pipeline with GPU-accelerated workers and object storage.",
    targetRps: 8_000,
    maxLatencyMs: 200,
    budgetUsd: 1000,
    slaAvailability: 0.999,
    readShare: 0.2,
    staticShare: 0.0,
    requiresPersistence: true,
    requiresHA: false,
    difficulty: 'Advanced',
    startingArchitecture: {
      nodes: [
        { id: 'client-node', type: 'client',          label: 'Client / Users',   position: { x: 80,  y: 220 } },
        { id: 'compute-1',   type: 'computeInstance', label: 'Compute Instance', position: { x: 380, y: 220 } },
        { id: 'sql-1',       type: 'sqlPrimary',      label: 'SQL Primary DB',   position: { x: 680, y: 220 } },
      ],
      edges: [
        { id: 'e1', source: 'client-node', target: 'compute-1' },
        { id: 'e2', source: 'compute-1',   target: 'sql-1' },
      ],
    },
  },
];

export const SCENARIO_MAP: Record<string, Scenario> = Object.fromEntries(
  SCENARIOS.map((s) => [s.id, s])
);
